-- ============================================================================
-- BharatInsight — Phase 0: Database Schema
-- Target: PostgreSQL 16 (bharatinsight_db)
--
-- This schema reflects the VERIFIED structure of the downloaded dataset
-- (see schema_report.md). Key findings baked into the design:
--   * food.f_id / menu.menu_id arrive as prefixed string codes ("fd123",
--     "mn45") — scripts/load_data.py parses them to integers at load time,
--     so the columns stay INTEGER here.
--   * menu.csv has no row-level key (menu_id repeats per restaurant), so the
--     menu table's honest primary key is the composite (restaurant_id,
--     food_id), with menu_id kept as a plain attribute.
--   * orders.csv has no order_id column at all → order_id below is a
--     SURROGATE key generated by PostgreSQL (IDENTITY). It is the only
--     non-source value in the schema, declared openly here.
--   * num_ratings arrives as banded text ("Too Few Ratings", "50+ ratings",
--     "1K+ ratings") — parsed to integers at load time.
--   * orders.sales_amount may be negative (refund/adjustment rows) — kept
--     intentionally; they are real transactions.
--
-- Re-runnable: every statement is guarded, so executing this file twice is
-- safe and idempotent.
-- ============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- users — customer dimension table
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    user_id                     INTEGER PRIMARY KEY,
    name                        VARCHAR(255),
    email                       VARCHAR(255),
    password                    VARCHAR(255),
    age                         SMALLINT,
    gender                      VARCHAR(20),
    marital_status              VARCHAR(20),
    occupation                  VARCHAR(100),
    monthly_income              VARCHAR(50),   -- banded text in source ("10001 to 25000" etc.); cast in Phase 2 if numeric
    educational_qualifications  VARCHAR(150),
    family_size                 SMALLINT
);

-- ----------------------------------------------------------------------------
-- restaurant — restaurant dimension table
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS restaurant (
    restaurant_id   INTEGER PRIMARY KEY,
    name            VARCHAR(255),
    location        VARCHAR(255),
    rating          NUMERIC(3, 1),   -- '--', 'NEW' etc. load as NULL (loader coerces)
    num_ratings     INTEGER,         -- 'Too Few Ratings'/'1K+ ratings' parsed by loader
    cost_for_two    NUMERIC(10, 2),  -- '₹ 200' etc. -> 200 (currency symbols stripped)
    cuisine         VARCHAR(150),
    license_number  VARCHAR(50),
    website_link    VARCHAR(500),
    address         TEXT
);

-- ----------------------------------------------------------------------------
-- food — food-item catalog (no dependencies)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS food (
    food_id         INTEGER PRIMARY KEY,   -- source format "fd123", parsed to int
    name            VARCHAR(255),
    veg_or_non_veg  VARCHAR(20)
);

-- ----------------------------------------------------------------------------
-- menu — restaurant ↔ food bridge with price
-- Real row key is (restaurant_id, food_id): menu_id is a per-restaurant menu
-- code that repeats across a restaurant's items, so it cannot be the PK.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS menu (
    menu_id         INTEGER,               -- source format "mn45", parsed to int
    restaurant_id   INTEGER NOT NULL,
    food_id         INTEGER NOT NULL,
    cuisine         VARCHAR(150),
    price           NUMERIC(10, 2),
    CONSTRAINT pk_menu PRIMARY KEY (restaurant_id, food_id),
    CONSTRAINT fk_menu_restaurant
        FOREIGN KEY (restaurant_id) REFERENCES restaurant (restaurant_id),
    CONSTRAINT fk_menu_food
        FOREIGN KEY (food_id) REFERENCES food (food_id)
);

-- ----------------------------------------------------------------------------
-- orders — fact table (all Phase 2/3 analytics run off this)
-- Source CSV provides no order id → surrogate IDENTITY key (declared, not
-- fabricated data: it's a row identifier, not a source attribute).
-- FK columns are deliberately NULLABLE: the source has order rows with
-- missing user/restaurant keys (verified Phase 0 finding). They are real
-- transactions — kept with NULL FK (Postgres FKs allow NULL), included in
-- revenue/customer aggregates, excluded only from restaurant-level rollups.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
    order_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_datetime  TIMESTAMP,
    quantity        INTEGER,
    sales_amount    NUMERIC(12, 2),  -- may be negative (refunds/adjustments) — real data
    currency        VARCHAR(10),     -- '\r' pollution stripped by loader's byte normalisation
    user_id         INTEGER,
    restaurant_id   INTEGER,
    CONSTRAINT fk_orders_user
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_orders_restaurant
        FOREIGN KEY (restaurant_id) REFERENCES restaurant (restaurant_id)
);

-- ----------------------------------------------------------------------------
-- Indexes — the columns hit hardest by Phase 2 queries
-- (monthly revenue trends, customer history, per-restaurant aggregates,
--  menu/food joins)
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_orders_order_datetime ON orders (order_datetime);
CREATE INDEX IF NOT EXISTS idx_orders_user_id        ON orders (user_id);
CREATE INDEX IF NOT EXISTS idx_orders_restaurant_id  ON orders (restaurant_id);
CREATE INDEX IF NOT EXISTS idx_menu_food_id          ON menu (food_id);
CREATE INDEX IF NOT EXISTS idx_menu_menu_id          ON menu (menu_id);

-- ----------------------------------------------------------------------------
-- Confirmation output
-- ----------------------------------------------------------------------------
DO $$
BEGIN
    RAISE NOTICE 'BharatInsight schema ready: users, restaurant, food, menu, orders (+ indexes)';
END $$;

COMMIT;
